### ISSUE TITLE
Add `--notify` flag

### ISSUE THREAD

**Issue by ihortom** [snowplow/checkup#2]
Add flags to main/root and `every` commands to facilitate testing and evaluation of the app. New flags to consider:

- `--no-print` and `--notify` to be used with the root application as in `checkup --no-print --notify`

Reason: `checkup` on its own prints the results of the checks to console and sends no notifications. We might adopt this command to run with cron instead of  `checkup every ...` as the updated list of checks in `checkup.json` requires an app restart.

- `--no-notify` to be used with `checkup every ...` to turn off notification even if it's in the configuration file. It's purely for the tests to reduce the noise.

**Comment by alexanderdean** [comment]
Better practice than a ticket called "Add extra flags" is to have a ticket per extra flag being added. This makes it easy to track changes in release notes / CHANGELOG, and means that each commit is a discrete unit of work... It also forces you to describe the behavior of each flag very precisely in the ticket.

**Comment by ihortom** [comment]
Taken onboard. Renaming this issue and creating additional ones for the other flags.

This ticket will deal with `--notify` flag as in `checkup --notify`. On its own, `checkup` will not send a notification even if it's set in the configuration file as it's only meant for a one-off run and thus simply produces the result of the checks in the console. We are likely to run the app this way regularly instead of `checkup every ...` command (which does send a notification if set up in the configuration file) to avoid the need to reboot the app on the configuration file change. 

The flag will enable the notification to be sent to PagerDuty (or any other service that might be adopted).
