### ISSUE TITLE
Add `--silent` flag

### ISSUE THREAD

**Issue by ihortom** [snowplow/checkup#5]
Add `--no-print` flag as in `checkup --no-print`. On its own, *checkup* produces the result of the checks in the console. We are likely to run the app this way regularly instead of `checkup every ...` command (to avoid reboot on configuration file change). The flag will silence the output to avoid unnecessary noise when run regularly instead of `checkup every ...` command. It could be used together with the `--notify` flag (see https://github.com/snowplow/checkup/issues/2) as in `checkup --no-print --notify` to facilitate a regular run of the app.

**Comment by alexanderdean** [comment]
Normally such options are called `--silent`

**Comment by ihortom** [comment]
OK, renaming...

It's to be run as `checkup --silent`.
