### ISSUE TITLE
New command `once`

### ISSUE THREAD

**Issue by ihortom** [snowplow/checkup#6]
To be used as `checkup once` in a similar fashion as `checkup every ...` with the following differences

- Runs once and exits rather than running as daemon
- Requires either storage or notification (or both) to be configured

**Comment by alexanderdean** [comment]
Does `every` *not* require notification to be configured? Why does `once` not store data?

**Comment by ihortom** [comment]
@alexanderdean - notification is an optional feature in "original" checkup (regardless of the command). With `once`, I'm forcing it to be a requirement. 

I do not store results with `once` command as the same functionality could be achieved with `checkup --store`. Besides, we do not want to store results in our environment anyway.

Actually, it's already implemented - https://github.com/snowplow/checkup/commit/1be7b95cbe18555ff39092173a9abfe230bd0157.

Let me know if you want to store with `once` in some fashion (by default or with a flag).

**Comment by alexanderdean** [comment]
I would store by default in `once`, just for consistency with `every`. We will eventually want to store by emitting a Snowplow event...

**Comment by ihortom** [comment]
Updated description of the command
